# Daten bereinigen (tidy data)

Eine wichtige Funktion ist es, Daten zu bereinigen. Das Grundprinzip
dafür ist, dass jede Zeile eine Beobachtung/ein Fall ist und jede Spalte
eine Variable abbildet. Was sich einfach anhört ist in der Praxis leider
nicht der Fall. Das Paket

**Fehlende Werte**

Fehlende Werte beschreibt R mit NA (non available oder non-assigned).
Berechnungen können durch fehlende Werte verfälscht oder nicht
ausgeführt werden. Doch dafür gibt es Lösungen.

```{r Fehlnde Werte}

# in diesem Beispiel haben wir unvollständige Werte in unserem Datensatz
# Diese sind mit NA codiert und werden so auch im tibble übernommen
age <- c(19,NA,25,31)
weight <- c(50,52,NA,76)
height <- c(162,168,177,NA)
name <- c("Maja","Ines","David","Jerome")

students2 <- data.frame(name, age, weight, height)
students2
s2 <- as_tibble(students2)
s2

# Berechnung Mittelwerte
# Bei der Berechnung werden die fehlenden Werte als NA bereits herausgerechnet
height <- mean(s2$height)
height == sum(162,168,177)/3 # beachte, dass durch 3 geteilt wird!


# Sicherer ist es, die fehlenden Werte zu entfernen oder zu unterdrücken. 

mean(s2$height,na.rm = TRUE)


```

### tidyr

tidyr ist ein umfangreiches Paket zur Datenbereinigung. Es wird vor
allem dafür eingesetzt, Datenstrukturen zu verändern. Dies werden wir
nur am Rande verwenden.

### Tibbles

Das Ziel einer guten Datenanalyse ist es, ein Tibble zu erstellen, also
einen einfachen Datenframe, in dem jede Zeile eine Beobachtung und jede
Spalte eine Variable darstellt. Das geht prinzipiell mit allen Daten.
Manchmal müssen dafür die Rohdaten verändert werden. Dazu verwenden wir
das Paket tidyR, [Cheatsheet
tidyR](https://raw.githubusercontent.com/rstudio/cheatsheets/main/tidyr.pdf)
(PDF)
